/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AmChart: typeof import('./src/components/AmChart.vue')['default']
    CardStatisticsHorizontal: typeof import('./src/@core/components/cards/CardStatisticsHorizontal.vue')['default']
    CardStatisticsVertical: typeof import('./src/@core/components/cards/CardStatisticsVertical.vue')['default']
    CardStatisticsWithImages: typeof import('./src/@core/components/cards/CardStatisticsWithImages.vue')['default']
    DigitTimer: typeof import('./src/components/screens/DigitTimer.vue')['default']
    ErrorHeader: typeof import('./src/components/ErrorHeader.vue')['default']
    GlobalLoading: typeof import('./src/components/GlobalLoading.vue')['default']
    LoadingOverlay: typeof import('./src/components/LoadingOverlay.vue')['default']
    ManagementMode: typeof import('./src/components/screens/ManagementMode.vue')['default']
    MerchantResultsPreview: typeof import('./src/components/screens/previews/MerchantResultsPreview.vue')['default']
    MerchantResultsScreen: typeof import('./src/components/screens/MerchantResultsScreen.vue')['default']
    MoreBtn: typeof import('./src/@core/components/MoreBtn.vue')['default']
    NobleResultsPreview: typeof import('./src/components/screens/previews/NobleResultsPreview.vue')['default']
    NobleResultsScreen: typeof import('./src/components/screens/NobleResultsScreen.vue')['default']
    PlaceholderPreview: typeof import('./src/components/screens/previews/PlaceholderPreview.vue')['default']
    PlaceholderScreen: typeof import('./src/components/screens/PlaceholderScreen.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScreenController: typeof import('./src/components/screens/ScreenController.vue')['default']
    ThemeSwitcher: typeof import('./src/@core/components/ThemeSwitcher.vue')['default']
    TimerPreview: typeof import('./src/components/screens/previews/TimerPreview.vue')['default']
    TimerScreen: typeof import('./src/components/screens/TimerScreen.vue')['default']
    UpgradeToPro: typeof import('./src/components/UpgradeToPro.vue')['default']
  }
}
